"""Adding fileds is_archived

Revision ID: 18ba2b337376
Revises: 61a1e1257102
Create Date: 2024-11-03 11:58:15.379114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ba2b337376'
down_revision: Union[str, None] = '61a1e1257102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_flow_categories', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.add_column('cash_flows', sa.Column('is_archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_flows', 'is_archived')
    op.drop_column('cash_flow_categories', 'is_archived')
    # ### end Alembic commands ###
