"""Delete field is_income

Revision ID: 1b7fb280a191
Revises: 19d827caf35a
Create Date: 2024-11-01 22:07:23.564974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7fb280a191'
down_revision: Union[str, None] = '19d827caf35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_flow_categories', 'is_income')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_flow_categories', sa.Column('is_income', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
